# Generated by Django 5.1.2 on 2024-10-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadstorage',
            name='address',
        ),
    ]
