# Generated by Django 5.1.2 on 2024-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_remove_loadstorage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstorage',
            name='address',
            field=models.CharField(default='Nothing', max_length=200),
        ),
        migrations.AddField(
            model_name='loadstorage',
            name='name',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
