# Generated by Django 5.1.2 on 2024-10-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_loadstorage_address_loadstorage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstorage',
            name='userId',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
