# Generated by Django 5.1.2 on 2024-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_loadstorage_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstorage',
            name='password',
            field=models.CharField(default='Nothing', max_length=200),
        ),
        migrations.AlterField(
            model_name='loadstorage',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
